[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "cd client && npm ci"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "cd client && npm start"
