[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "cd server && npm ci"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd server && npm run build"
]

[start]
cmd = "cd server && npm start"
